# Generated by Django 5.2.5 on 2025-08-19 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0002_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelstasksreal',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.labels'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', through='tasks.LabelsTasksReal', to='labels.labels', verbose_name='Labels'),
        ),
    ]
